### ISSUE TITLE
What's the deal with this package?

### ISSUE THREAD

**Issue by tredondo** [vansergen/coinbase-pro#25]
Like, clearly it's not official, since Coinbase deprecated everything and didn't bother to pay like 0.0001% of their billions of dollars to someone to publish a Node package so people would write bots to earn Coinbase commissions :man_facepalming:

Anyway, it would be useful to add some info at the top of the README like @bennyn did for https://github.com/bennyn/coinbase-pro-node. How's this library different from his? What are features? What's the history? What are the goals? Any auditing?

Thanks

**Comment by vansergen** [comment]
@meteorpublish You are very welcome to open a PR. 

> How's this library different from his? 

I did not have a chance to look at it. So, I you can open a [new issue](https://github.com/bennyn/coinbase-pro-node/issues/new) and ask the same question. Anyway, the best way is to try both libraries and choose which one fits your needs.
